#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: vct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vct
  template:
    metadata:
      labels:
        app: vct
    spec:
      containers:
        - name: vct
          envFrom:
            - configMapRef:
                name: vct-env
            - secretRef:
                name: vct-env-secret
          image: vct:latest
          args: ["start"]
          ports:
            - containerPort: 8081
              protocol: TCP
              name: http-port
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http-port
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
