#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue

generatorOptions: {}


configMapGenerator:
- envs:
  - config.env
  name: orb-env

secretGenerator:
- envs:
  - secret.env
  name: orb-env-secret

resources:
- deployment.yml
- service.yml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: orb
  newName: ghcr.io/trustbloc-cicd/orb
  newTag: v0.1.3-snapshot-1543586
