#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: ipfs
spec:
  ports:
  - name: ipfs-port
    port: 5001
    protocol: TCP
    targetPort: ipfs-port
  selector:
    app: ipfs
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: ipfs-p2p-tcp
spec:
  ports:
  - name: ipfs-swarm-port-tcp
    port: 4001
    protocol: TCP
    targetPort: ipfs-swarm-port-tcp
  selector:
    app: ipfs
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: ipfs-p2p-udp
spec:
  ports:
  - name: ipfs-swarm-port-udp
    port: 4001
    protocol: UDP
    targetPort: ipfs-swarm-port-udp
  selector:
    app: ipfs
status:
  loadBalancer: {}
