#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

serve:
  proxy:
    port: 4455
  api:
    port: 4456

access_rules:
  repositories:
    - file:///etc/rules/access-rules.json
  matching_strategy: regexp

authenticators:
  oauth2_introspection:
    enabled: true
    config:
      introspection_url: https://auth-hydra-admin.||DOMAIN||/oauth2/introspect
      scope_strategy: exact
  noop:
    enabled: true

authorizers:
  allow:
    enabled: true

mutators:
  header:
    enabled: true
    config:
      headers:
        X-Tenant-ID: "{{ print .Subject }}"
        X-API-Key: "rw_token"
  noop:
    enabled: true
