#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue

generatorOptions: {}

commonLabels:
  group: core

configMapGenerator:
- envs:
  - config.env
  name: kms-env

secretGenerator:
- envs:
  - secret.env
  name: kms-env-secret

resources:
- deployment.yml
- service.yml


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: kms
  newName: ghcr.io/trustbloc-cicd/kms
  newTag: v0.1.9-snapshot-9389ad5
