#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# Annotations to add to all resources
#commonAnnotations:
#  someName: someValue

generatorOptions: {}

configMapGenerator:
- envs:
  - config.env
  name: web-env
- files:
  - default.conf.template
  name: nginx-config-template

secretGenerator:
- envs:
  - secret.env
  name: web-env-secret

resources:
- deployment.yml
- service.yml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: wallet-web
  newName: ghcr.io/trustbloc-cicd/wallet-web
  newTag: v0.1.8-snapshot-27486ad
